const lessonTitle = "穿越时空的硬币";

const lessonData = [
    // 正文第 1 段
    ["9岁", "jiǔ suì", "9 years old", "9 tahun"],
    ["那年", "nà nián", "that year", "tahun itu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["被", "bèi", "by (passive particle)", "di- / oleh"],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["送到", "sòng dào", "sent to", "dihantar ke"],
    ["老区", "lǎo qū", "old revolutionary area", "kawasan lama"],
    ["龙岩", "lóng yán", "Longyan (a place)", "Longyan (nama tempat)"],
    ["的", "de", "particle", ""],
    ["外婆家", "wài pó jiā", "maternal grandmother's home", "rumah nenek"],
    ["，", "", "", ""],
    ["并", "bìng", "and also", "serta / dan"],
    ["转到", "zhuǎn dào", "transferred to (school)", "berpindah ke"],
    ["当地", "dāng dì", "local", "tempatan"],
    ["一所", "yì suǒ", "a (measure word for schools)", "sebuah"],
    ["叫", "jiào", "called / named", "bernama / dipanggil"],
    ["兴田", "xīng tián", "Xingtian (school name)", "Xingtian"],
    ["的", "de", "particle", ""],
    ["小学", "xiǎo xué", "primary school", "sekolah rendah"],
    ["。", "", "", ""],
    ["父母", "fù mǔ", "parents", "Ibu bapa"],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["来看我", "lái kàn wǒ", "come to see me", "datang melawat saya"],
    ["，", "", "", ""],
    ["总", "zǒng", "always", "sentiasa / pasti"],
    ["给我", "gěi wǒ", "give me", "memberi saya"],
    ["留些", "liú xiē", "leave some", "meninggalkan sedikit"],
    ["零用钱", "líng yòng qián", "pocket money / allowance", "duit saku / wang saku"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["都", "dōu", "all", "pun / semua"],
    ["一一", "yī yī", "one by one", "satu demi satu"],
    ["攒起来", "zǎn qǐ lái", "saved up / accumulated", "mengumpul / menyimpan"],
    ["，", "", "", ""],
    ["放在", "fàng zài", "put inside", "meletakkan di dalam"],
    ["一个", "yí gè", "a / one", "sebuah"],
    ["小铁盒", "xiǎo tiě hé", "small iron box", "kotak besi kecil"],
    ["里", "lǐ", "inside", "dalam / di dalam"],
    ["。", "", "", ""],
    ["因", "yīn", "because / as", "Kerana / oleh sebab"],
    ["当时的", "dāng shí de", "at that time's", "pada masa itu punya"],
    ["同学", "tóng xué", "classmates", "rakan sekelas"],
    ["大都", "dà dōu", "mostly", "kebanyakannya"],
    ["是", "shì", "were", "adalah"],
    ["些", "xiē", "some", "beberapa / golongan"],
    ["穷苦", "qióng kǔ", "poor / poverty-stricken", "miskin / susah"],
    ["人家", "rén jiā", "families", "keluarga"],
    ["的", "de", "particle", "yang"],
    ["孩子", "hái zi", "children", "anak-anak"],
    ["，", "", "", ""],
    ["因而", "yīn ér", "therefore", "oleh itu / maka"],
    ["我", "wǒ", "I", "saya"],
    ["俨然", "yǎn rán", "just like / rowingly appear as", "seolah-olah / tampaknya seperti"],
    ["成了", "chéng le", "became", "menjadi"],
    ["班上的", "bān shàng de", "in the class'", "dalam kelas punya"],
    ["小富翁", "xiǎo fù wēng", "little rich man", "orang kaya kecil"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["一天", "yì tiān", "One day", "Pada suatu hari"],
    ["，", "", "", ""],
    ["班上", "bān shàng", "in the class", "dalam kelas"],
    ["一位", "yí wèi", "a (measure word for person)", "seorang"],
    ["同学", "tóng xué", "classmate", "rakan sekelas"],
    ["找到", "zhǎo dào", "found / approached", "menemui"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["小声地", "xiǎo shēng de", "in a low voice / quietly", "dengan suara perlahan / berbisik"],
    ["对", "duì", "to / towards", "kepada"],
    ["我", "wǒ", "me", "saya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "Kamu"],
    ["能不能", "néng bù néng", "whether or not you can", "bolehkah atau tidak"],
    ["借我", "jiè wǒ", "lend me", "pinjamkan saya"],
    ["两块钱", "liǎng kuài qián", "two dollars (yuan)", "dua ringgit / dua yuan"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["在", "zài", "at", "Pada / ketika"],
    ["当时", "dāng shí", "that time", "masa itu"],
    ["，", "", "", ""],
    ["两块钱", "liǎng kuài qián", "two dollars", "dua ringgit"],
    ["对", "duì", "for / to", "kepada"],
    ["一个", "yí gè", "a", "seorang"],
    ["小孩", "xiǎo hái", "child", "budak / anak kecil"],
    ["来说", "lái shuō", "as far as... is concerned", "secara amnya"],
    ["，", "", "", ""],
    ["是", "shì", "was", "adalah"],
    ["笔", "bǐ", "a sum of (measure word for money)", "satu jumlah / sekumpul"],
    ["不菲的", "bù fěi de", "not small / considerable sum", "bukan kepalang / agak besar / bernilai"],
    ["数目", "shù mù", "amount / sum", "jumlah / bilangan"],
    ["。", "", "", ""],
    ["看到", "kàn dào", "seeing", "Melihat / nampak"],
    ["我", "wǒ", "I", "saya"],
    ["脸上", "liǎn shàng", "on the face", "pada muka"],
    ["的", "de", "particle", ""],
    ["为难", "wéi nán", "hesitation / embarrassment", "keberatan / serba salah"],
    ["，", "", "", ""],
    ["同学", "tóng xué", "classmate", "rakan sekelas itu"],
    ["又", "yòu", "again", "pula / lagi"],
    ["低着头", "dī zhe tóu", "hanging head low", "menundukkan kepala"],
    ["说", "shuō", "said", "dan berkata"],
    ["那钱", "nà qián", "that money", "wang itu"],
    ["他", "tā", "he", "dia"],
    ["正", "zhèng", "currently", "sedang"],
    ["急用", "jí yòng", "need urgently", "sangat memerlukan / cemas guna"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "serta"],
    ["向", "xiàng", "to / towards", "kepada"],
    ["我", "wǒ", "me", "saya"],
    ["保证", "bǎo zhèng", "guarantee / promise", "berjanji / menjamin"],
    ["一星期", "yì xīng qī", "one week", "seminggu / satu minggu"],
    ["内", "nèi", "within", "dalam tempoh"],
    ["一定", "yí dìng", "definitely / surely", "pasti / tentu akan"],
    ["还我", "huán wǒ", "return to me", "memulangkan kepada saya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["想了", "xiǎng le", "thought for", "berfikir"],
    ["一会儿", "yí huì r", "a moment", "sebentar / sekejap"],
    ["，", "", "", ""],
    ["于是", "yú shì", "therefore / so", "maka / oleh itu"],
    ["小心翼翼地", "xiǎo xīn yì yì de", "cautiously / with extreme care", "dengan sangat berhati-hati"],
    ["从", "cóng", "from", "dari"],
    ["铁盒", "tiě hé", "iron box", "kotak besi"],
    ["里", "lǐ", "inside", "dalam"],
    ["取出", "qǔ chū", "took out", "mengeluarkan"],
    ["钱", "qián", "money", "wang"],
    ["，", "", "", ""],
    ["递到", "dì dào", "handed to", "menyerahkan ke / menghulurkan ke"],
    ["他", "tā", "his", "dia punya"],
    ["手里", "shǒu lǐ", "hand", "tangan"],
    ["。", "", "", ""],
    ["同学", "tóng xué", "classmate", "Rakan sekelas itu punya"],
    ["瘦黑的", "shòu hēi de", "thin and dark", "muka yang kurus dan gelap"],
    ["脸", "liǎn", "face", "muka"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["变得", "biàn de", "became", "menjadi"],
    ["通红", "tōng hóng", "flushed red", "merah padam"],
    ["，", "", "", ""],
    ["还", "hái", "also / furthermore", "malah / juga"],
    ["从", "cóng", "from", "dari"],
    ["书包", "shū bāo", "schoolbag", "dalam beg sekolah"],
    ["里", "lǐ", "inside", "dalam"],
    ["掏出", "tāo chū", "pulled out / took out", "mengeluarkan / menyeluk keluar"],
    ["一只", "yì zhī", "a (measure word for paper boat)", "sebiji / seekor"],
    ["漂亮的", "piào liang de", "beautiful", "yang cantik"],
    ["纸船", "zhǐ chuán", "paper boat", "perahu kertas"],
    ["，", "", "", ""],
    ["放到", "fàng dào", "placed into", "meletakkan ke dalam"],
    ["我", "wǒ", "my", "saya punya"],
    ["手里", "shǒu lǐ", "hand", "tangan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["几天", "jǐ tiān", "A few days", "Beberapa hari"],
    ["后", "hòu", "later", "kemudian"],
    ["，", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["把", "bǎ", "structural particle", ""],
    ["我", "wǒ", "me", "saya"],
    ["接回", "jiē huí", "took back / picked back", "mengambil saya pulang ke"],
    ["福州", "fú zhōu", "Fuzhou (a city)", "Fuzhou"],
    ["。", "", "", ""],
    ["到了", "dào le", "arrived at", "Tiba di"],
    ["新学校", "xīn xué xiào", "new school", "sekolah baru"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["时常", "shí cháng", "often / frequently", "sering kali / selalu"],
    ["还会", "hái huì", "still would", "masih akan"],
    ["想起", "xiǎng qǐ", "think of / recall", "teringat akan"],
    ["那", "nà", "those", "itu"],
    ["两块钱", "liǎng kuài qián", "two dollars", "dua ringgit"],
    ["，", "", "", ""],
    ["很有", "hěn yǒu", "had quite a few", "mempunyai beberapa"],
    ["几分", "jǐ fēn", "somewhat / a bit of", "sedikit perasaan"],
    ["后悔", "hòu huǐ", "regret", "menyesal"],
    ["。", "", "", ""],
    ["直至", "zhí zhì", "up until", "Sehinggalah / sampai"],
    ["后来", "hòu lái", "later on", "kemudian hari"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["由悔生恨", "yóu huǐ shēng hèn", "regret turned into hatred", "daripada menyesal menjadi benci"],
    ["，", "", "", ""],
    ["竟", "jìng", "unexpectedly / actually", "malah / sampai hati"],
    ["翻出了", "fān chū le", "dug out / found out", "menyelongkar keluar"],
    ["同学", "tóng xué", "classmate", "rakan sekelas itu punya"],
    ["送的", "sòng de", "given", "yang dihadiahkan"],
    ["那只", "nà zhī", "that", "sebiji / yang itu"],
    ["纸船", "zhǐ chuán", "paper boat", "perahu kertas"],
    ["，", "", "", ""],
    ["找来", "zhǎo lái", "found / looked for", "mencari / mengambil"],
    ["竹鞭", "zhú biān", "bamboo whip / cane", "pemicu bambu / rotan buluh"],
    ["狠狠", "hěn hěn", "viciously / fiercely", "dengan cukup kuat / sepuas-puasnya"],
    ["抽打", "chōu dǎ", "whipped / thrashed", "menyebat / memukul"],
    ["了", "le", "particle", ""],
    ["一番", "yì fān", "a round (measure word for action)", "sekali"],
    ["，", "", "", ""],
    ["以", "yǐ", "in order to", "untuk"],
    ["泄", "xiè", "vent / release", "melepaskan / melepaskan geram"],
    ["心头", "xīn tóu", "heart's / mind's", "dalam hati punya"],
    ["怨气", "yuàn qì", "resentment / anger", "kemarahan / rasa geram"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["一晃", "yì huǎng", "In a flash / quickly", "Pejam celik / dalam sekelip mata"],
    ["十几年", "shí jǐ nián", "more than ten years", "belasan tahun"],
    ["过去了", "guò qù le", "passed by", "telah berlalu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["已", "yǐ", "already", "sudah pun"],
    ["大学毕业", "dà xué bì yè", "graduated from university", "tamat universiti / lulus universiti"],
    ["。", "", "", ""],
    ["一年", "yì nián", "One year", "Pada suatu tahun"],
    ["初冬", "chū dōng", "early winter", "awal musim sejuk"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["收到", "shōu dào", "received", "menerima"],
    ["一个", "yí gè", "a", "sebuah / satu"],
    ["加拿大", "jiā ná dà", "Canada", "Kanada"],
    ["寄来的", "jì lái de", "sent from", "yang dihantar dari"],
    ["包裹", "bāo guǒ", "parcel / package", "bingkisan / paket /包裹"],
    ["。", "", "", ""],
    ["疑惑地", "yí huò de", "puzzledly / doubtfully", "dengan penuh curiga / hairan"],
    ["打开", "dǎ kāi", "opened", "membuka"],
    ["，", "", "", ""],
    ["只见", "zhǐ jiàn", "only to see", "hanya kelihatan"],
    ["里面", "lǐ miàn", "inside", "di dalam"],
    ["有一个", "yǒu yí gè", "there was a", "ada satu"],
    ["盒子", "hé zi", "box", "kotak"],
    ["装满了", "zhuāng mǎn le", "filled with", "dipenuhi dengan"],
    ["枫叶", "fēng yè", "maple leaves", "daun mapel"],
    ["，", "", "", ""],
    ["枫叶", "fēng yè", "maple leaves", "daun mapel"],
    ["上", "shàng", "on", "atas"],
    ["还", "hái", "also", "juga"],
    ["躺着", "tǎng zhe", "lying", "terletak / terbaring"],
    ["一封信", "yì fēng xìn", "a letter", "sepucuk surat"],
    ["和", "hé", "and", "dan"],
    ["一只", "yì zhī", "a", "sebuah / satu"],
    ["陈旧的", "chén jiù de", "old / worn-out", "yang usang / buruk / lama"],
    ["小纸袋", "xiǎo zhǐ dài", "small paper bag", "beg kertas kecil"],
    ["。", "", "", ""],
    ["信里", "xìn lǐ", "In the letter", "Dalam surat itu"],
    ["署着个", "shǔ zhe gè", "signed with a", "ditandatangani dengan nama"],
    ["生疏的", "shēng shū de", "unfamiliar / strange", "yang asing / tidak dikenali"],
    ["名字", "míng zi", "name", "nama"],
    ["，", "", "", ""],
    ["想了", "xiǎng le", "thought for", "berfikir"],
    ["好一会儿", "hǎo yí huì r", "a good while", "agak lama / sejenak"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["才", "cái", "only then", "baru / barulah"],
    ["记起", "jì qǐ", "remembered / recalled", "teringat semula"],
    ["是", "shì", "was", "adalah"],
    ["那年", "nà nián", "that year", "tahun itu punya"],
    ["曾", "céng", "once", "pernah"],
    ["向我", "xiàng wǒ", "from me", "kepada saya / daripada saya"],
    ["借过", "jiè guò", "borrowed", "meminjam"],
    ["两块钱", "liǎng kuài qián", "two dollars", "dua ringgit"],
    ["的", "de", "particle", ""],
    ["同学", "tóng xué", "classmate", "rakan sekelas"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["原来", "yuán lái", "It turned out that", "Rupa-rupanya / asalnya"],
    ["，", "", "", ""],
    ["当年", "dāng nián", "in those years", "pada tahun itu"],
    ["同学的", "tóng xué de", "classmate's", "rakan sekelas punya"],
    ["父亲", "fù qīn", "father", "bapa / ayah"],
    ["在外", "zài wài", "outside", "di luar"],
    ["打工", "dǎ gōng", "working / doing manual labor", "bekerja / mencari rezeki"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["母亲的", "mā ma de", "mother's", "ibu punya"],
    ["病情", "bìng qíng", "illness state / condition", "keadaan penyakit / kesihatan"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["恶化", "è huà", "worsened / deteriorated", "menjadi teruk / merosot"],
    ["，", "", "", ""],
    ["可", "kě", "but", "namun / tetapi"],
    ["家里的", "jiā lǐ de", "at home's", "rumah punya"],
    ["钱", "qián", "money", "wang"],
    ["已", "yǐ", "already", "sudah"],
    ["不够", "bú gòu", "not enough", "tidak mencukupi untuk"],
    ["抓药", "zhuā yào", "fill a prescription / buy herbal medicine", "membeli ubat / mengambil ubat"],
    ["。", "", "", ""],
    ["情急之中", "qíng jí zhī zhōng", "in a moment of desperation", "dalam keadaan cemas / terdesak"],
    ["他", "tā", "he", "dia"],
    ["想到了", "xiǎng dào le", "thought of", "teringat akan"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["向我", "xiàng wǒ", "from me", "daripada saya"],
    ["借了", "jiè le", "borrowed", "meminjam"],
    ["两块钱", "liǎng kuài qián", "two dollars", "dua ringgit"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["又", "yòu", "also", "pula / juga"],
    ["担心", "dān xīn", "worried", "bimbang / risau"],
    ["父亲", "fù qīn", "father", "bapa"],
    ["不能", "bù néng", "could not", "tidak dapat"],
    ["及时", "jí shí", "in time / timely", "tepat pada masanya"],
    ["寄钱", "jì qián", "send money", "mengirimkan wang"],
    ["回来", "huí lái", "back", "pulang"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu / maka"],
    ["每晚", "měi wǎn", "every night", "setiap malam"],
    ["趁", "chèn", "take advantage of (mother sleeping)", "sementara / mengambil kesempatan ketika"],
    ["母亲", "mā ma", "mother", "ibu"],
    ["熟睡", "shú shuì", "fast asleep", "tidur nyenyak"],
    ["后", "hòu", "after", "selepas"],
    ["出去", "chū qù", "go out", "keluar"],
    ["捡废铁", "jiǎn fèi tiě", "scavenge scrap iron", "mengutip besi buruk"],
    ["卖钱", "mài qián", "sell for money", "untuk dijual"],
    ["。", "", "", ""],
    ["一次", "yí cì", "Once / one time", "Suatu kali"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["在", "zài", "in / at", "di / dalam"],
    ["一条", "yì tiáo", "a (measure word for ditch)", "sebatang"],
    ["臭水沟", "chòu shuǐ gōu", "smelly ditch / gutter", "longkang busuk"],
    ["里", "lǐ", "inside", "dalam"],
    ["发现", "fā xiàn", "found", "menemui"],
    ["一枚", "yì méi", "a (measure word for coin)", "sekeping"],
    ["变了形的", "biàn le xíng de", "deformed / distorted", "yang kemek / berubah bentuk"],
    ["硬币", "yìng bì", "coin", "duit syiling"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["捡到了", "jiǎn dào le", "picked up", "menemui / mendapat"],
    ["宝", "bǎo", "treasure", "harta karun / barang berharga"],
    ["，", "", "", ""],
    ["回到家", "huí dào jiā", "returned home", "pulang ke rumah"],
    ["用", "yòng", "use", "menggunakan"],
    ["一块布", "yí kuài bù", "a piece of cloth", "sehelai kain"],
    ["裹着", "guǒ zhe", "wrapping", "membungkusnya"],
    ["，", "", "", ""],
    ["再用", "zài yòng", "then use", "kemudian menggunakan"],
    ["小铁锤", "xiǎo tiě chuí", "small iron hammer", "tukul besi kecil"],
    ["一下一下", "yí xià yí xià", "strike by strike", "sedikit demi sedikit / ketukan demi ketukan"],
    ["轻轻地", "qīng qīng de", "gently", "dengan perlahan / lembut"],
    ["锤平", "chuí píng", "hammer flat", "mengetuk sehingga rata"],
    ["。", "", "", ""],
    ["等到", "děng dào", "by the time / when", "Apabila / menjelang"],
    ["他", "tā", "he", "dia"],
    ["凑齐了", "còu qí le", "scraped together / gathered enough", "mencukupkan jumlah / mengumpul cukup"],
    ["钱", "qián", "money", "wang"],
    ["，", "", "", ""],
    ["没想到", "méi xiǎng dào", "unexpectedly", "tidak disangka"],
    ["我", "wǒ", "I", "saya"],
    ["已", "yǐ", "already", "sudah pun"],
    ["转学了", "zhuǎn xué le", "transferred schools", "berpindah sekolah"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["一直", "yī zhí", "all along", "sentiasa / berterusan"],
    ["都", "dōu", "all", "pun"],
    ["设法", "shè fǎ", "tried mechanisms to / did best", "berikhtiar / cuba mencari jalan"],
    ["和我", "hé wǒ", "with me", "dengan saya"],
    ["联系", "lián xì", "contact / get in touch", "menghubungi"],
    ["，", "", "", ""],
    ["直到", "zhí dào", "until", "sehingga"],
    ["大学毕业", "dà xué bì yè", "graduated university", "tamat universiti"],
    ["去了", "qù le", "went to", "pergi ke"],
    ["加拿大", "jiā ná dà", "Canada", "Kanada"],
    ["，", "", "", ""],
    ["都", "dōu", "even", "pun"],
    ["没", "méi", "did not", "tidak"],
    ["联系上", "lián xì shàng", "connect with / get in touch", "berjaya hubungi"],
    ["。", "", "", ""],
    ["直至", "zhí zhì", "until", "Sehinggalah"],
    ["一个多月", "yí gè duō yuè", "more than a month", "sebulan lebih"],
    ["前", "qián", "ago", "lalu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["登入了", "dēng rù le", "logged into", "mendaftar masuk ke"],
    ["网上的", "wǎng shàng de", "online's", "dalam talian punya"],
    ["同学通讯录", "tóng xué tōng xùn lù", "alumni directory / contact list", "buku alumni / direktori rakan sekelas"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["才", "cái", "only then", "barulah"],
    ["找到了", "zhǎo dào le", "found", "menemui"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["那一刻", "nà yí kè", "at that moment", "pada saat itu"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["兴奋无比", "xīng fèn wú bǐ", "incomparably excited", "teramat gembira / seronok bukan kepalang"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["同学", "tóng xué", "Classmate", "Rakan sekelas itu"],
    ["还在", "hái zài", "also in", "juga dalam"],
    ["信里", "xìn lǐ", "the letter", "surat itu"],
    ["告诉我", "gào su wǒ", "told me", "memberitahu saya"],
    ["，", "", "", ""],
    ["一直", "yī zhí", "all along", "sentiasa / selama ini"],
    ["以来", "yǐ lái", "since", "sejak"],
    ["他", "tā", "he", "dia"],
    ["都", "dōu", "all", "pun"],
    ["希望能", "xī wàng néng", "hoped could", "berharap dapat"],
    ["送我", "sòng wǒ", "send me", "hadiahkan saya"],
    ["一份", "yí fèn", "a (measure word for gifts)", "satu"],
    ["礼物", "lǐ wù", "gift / present", "hadiah"],
    ["。", "", "", ""],
    ["可", "kě", "but", "Namun"],
    ["无论", "wú lùn", "no matter", "tidak kira / walau apa pun"],
    ["送什么", "sòng shén me", "what to send", "yang dihadiahkan"],
    ["，", "", "", ""],
    ["都", "dōu", "all", "pun"],
    ["难以", "nán yǐ", "difficult to", "sukar untuk"],
    ["表达", "nán yǐ biǎo dá", "express / convey", "menyatakan / menggambarkan"],
    ["他", "tā", "he", "dia"],
    ["和", "hé", "and", "dan"],
    ["母亲", "mā ma", "mother", "ibu dia"],
    ["对我的", "duì wǒ de", "towards me's", "terhadap saya punya"],
    ["感激", "gǎn jī", "gratitude / appreciation", "penghargaan / terima kasih"],
    ["。", "", "", ""],
    ["最后", "zuì hòu", "Finally", "Akhirnya"],
    ["他就", "tā jiù", "he then", "dia pun"],
    ["从", "cóng", "from", "dari"],
    ["后山", "hòu shān", "back hill", "bukit belakang rumah"],
    ["成千上万", "chéng qiān shàng wàn", "thousands and thousands", "beribu-ribu / berlaksa-laksa"],
    ["的", "de", "particle", "yang"],
    ["枫叶", "fēng yè", "maple leaves", "daun mapel"],
    ["中", "zhōng", "among", "dalam kalangan / antara"],
    ["，", "", "", ""],
    ["选出", "xuǎn chū", "selected", "memilih keluar"],
    ["两百片", "liǎng bǎi piàn", "two hundred pieces", "dua ratus helai"],
    ["漂亮的", "piào liang de", "beautiful", "yang cantik"],
    ["叶子", "yè zi", "leaves", "daun"],
    ["送给我", "sòng gěi wǒ", "give to me", "kepada saya"],
    ["。", "", "", ""],
    ["他说", "tā shuō", "He said", "Dia berkata"],
    ["，", "", "", ""],
    ["每一片", "měi yí piàn", "every single piece", "setiap helai"],
    ["叶子", "yè zi", "leaf", "daun"],
    ["都", "dōu", "all", "pun"],
    ["承载着", "chéng zài zhe", "carries / bears", "membawa / sarat dengan"],
    ["他", "tā", "he", "dia"],
    ["与", "yǔ", "and", "dan"],
    ["母亲", "mā ma", "mother", "ibu"],
    ["对我的", "duì wǒ de", "towards me's", "terhadap saya punya"],
    ["感激", "gǎn jī", "gratitude", "penghargaan / terima kasih"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["那装着", "nà zhuāng zhe", "That containing", "Yang mengandungi"],
    ["两块", "liǎng kuài", "two pieces", "dua keping"],
    ["硬币", "yìng bì", "coins", "duit syiling"],
    ["的", "de", "particle", ""],
    ["纸袋", "zhǐ dài", "paper bag", "beg kertas itu"],
    ["，", "", "", ""],
    ["是用", "shì yòng", "was using", "adalah menggunakan"],
    ["作业本", "zuò yè běn", "exercise book", "buku latihan punya"],
    ["封面", "fēng miàn", "cover", "muka depan / kulit luar"],
    ["糊成的", "hú chéng de", "pasted together / made of", "dilekat / dibuat daripada"],
    ["，", "", "", ""],
    ["上面", "shàng miàn", "above / on it", "di atasnya"],
    ["印有", "yìn yǒu", "printed with", "bercetak dengan perkataan"],
    ["“", "", "", ""],
    ["兴田小学", "xīng tián xiǎo xué", "Xingtian Primary School", "Sekolah Rendah Xingtian"],
    ["”", "", "", ""],
    ["的", "de", "particle", ""],
    ["字样", "zì yàng", "printed words", "tulisan"],
    ["，", "", "", ""],
    ["姓名栏", "xìng míng lán", "name column / field", "ruangan nama"],
    ["里", "lǐ", "inside", "dalam"],
    ["同学的", "tóng xué de", "classmate's", "rakan sekelas punya"],
    ["名字", "míng zi", "name", "nama"],
    ["已", "yǐ", "already", "sudah pun"],
    ["有些", "yǒu xiē", "somewhat / slightly", "agak / sedikit"],
    ["模糊", "mó hu", "blurred / faded", "kabur / pudar"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["轻抖一下", "qīng dǒu yí xià", "gently shook once", "menggonggong / menggoncang perlahan sekali"],
    ["纸袋", "zhǐ dài", "paper bag", "beg kertas itu"],
    ["，", "", "", ""],
    ["里面", "lǐ miàn", "inside", "di dalamnya"],
    ["曾", "céng", "once", "pernah"],
    ["陪着", "péi zhe", "accompanied", "menemani / bersama-senasib"],
    ["同学", "tóng xué", "classmate", "rakan sekelas itu"],
    ["走过", "zǒu guò", "walked through", "mengharungi"],
    ["小学", "xiǎo xué", "primary school", "sekolah rendah"],
    ["、", "", "", ""],
    ["中学", "zhōng xué", "secondary school", "sekolah menengah"],
    ["、", "", "", ""],
    ["大学", "dà xué", "university", "universiti"],
    ["，", "", "", ""],
    ["又", "yòu", "and also", "malah juga"],
    ["跨过", "kuà guò", "crossed over", "merentasi"],
    ["茫茫", "máng máng", "vast / boundless", "luas terbentang / lautan luas"],
    ["大洋", "dà yáng", "ocean", "samudra / lautan besar"],
    ["的", "de", "particle", "yang"],
    ["硬币", "yìng bì", "coins", "duit syiling"],
    ["哗哗作响", "huā huā zuò xiǎng", "clinked / rattled", "berbunyi gemerincing 'hua-hua'"],
    ["，", "", "", ""],
    ["份量", "fèn liàng", "weight / significance", "beratnya / nilainya"],
    ["陡增", "dǒu zēng", "suddenly increased", "meningkat secara mendadak"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["眼里", "yǎn lǐ", "in the eyes", "mata / dalam mata"],
    ["一下子", "yí xià zi", "all of a sudden", "tiba-tiba / dalam sekelip mata"],
    ["迷蒙", "mí méng", "blurred (with tears) / misty", "menjadi kabur / berkaca-kaca dengan air mata"],
    ["：", "", "", ""],
    ["为", "wèi", "for (because of)", "kerana"],
    ["当年", "dāng nián", "in those years", "pada tahun itu"],
    ["同学", "tóng xué", "classmate", "rakan sekelas itu"],
    ["握着", "wò zhe", "holding", "memegang"],
    ["锤子", "chuí zi", "hammer", "tukul besi"],
    ["的", "de", "particle", ""],
    ["小小的", "xiǎo xiǎo de", "small / tiny", "yang kecil"],
    ["背影", "bèi yǐng", "view of back", "susuk belakang"],
    ["，", "", "", ""],
    ["更为", "gèng wèi", "and even more for", "malah lebih-lebih lagi kerana"],
    ["那", "nà", "that", "yang"],
    ["挥舞着", "huī wǔ zhe", "waving / brandishing", "mengayun-ayunkan"],
    ["竹鞭", "zhú biān", "bamboo whip", "pemukul buluh"],
    ["一腔", "yì qiāng", "a bellyful of / full of", "sarat dengan / segenap"],
    ["怨恨", "yuàn hèn", "resentment", "perasaan dendam / marah"],
    ["的", "de", "particle", "yang"],
    ["少年", "shào nián", "youth / teenager", "remaja / budak lelaki"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 文末出处

    ["（", "", "", ""],
    ["麦田", "mài tián", "Mai Tian (Author)", "Mai Tian (Penulis)"],
    ["《", "", "", ""],
    ["穿越时空的硬币", "chuān yuè shí kōng de yìng bì", "The Coin Transcending Time and Space", "Duit Syiling Merentasi Masa dan Ruang"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
